### PR TITLE
Updated to unity 2020

### PR DESCRIPTION
**Pull request by Mortecha**
Updated this so that it now uses 2020 instead of 2017. Fixed an issue where there was ambiguity between System.Tuple and Eppy.Tuple, assumed you wanted to use Eppy.Tuple so made that the one it uses. Fixed some calls that have now been made obsolete. 

The missing prefabs are still present and I hope that these get added in to make things work nicely.

### CODE REVIEW

**Comment by oddmax** [comment]
That's awesome, thank you for doing this work! Let me take a look and fix missing prefabs finally :)

**Comment by oddmax** [comment]
I'm not sure why there is a diff in every file. I guess because of different line endings. Let me check if I could fix that.

**Comment by ghost** [comment]
I was wondering what was happening there and it's definitely the line endings. I think it's something I have to fix on my end. I'll change the global git settings on my pc as shown here: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings. 

I'll fix this up as this is abit of a mess and it hides the actual changes that have been made.

**Comment by ghost** [comment]
Should be all ready to go now:)

**Comment by Mortecha** [comment]
Should be all ready to go now:)

**Review by oddmax — APPROVED** [review]

**Pull request merged**
